-- MySQL Script generated by MySQL Workbench
-- Tue Oct  4 14:07:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema navigators_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema navigators_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `navigators_db` DEFAULT CHARACTER SET utf8 ;
USE `navigators_db` ;

-- -----------------------------------------------------
-- Table `navigators_db`.`navigators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `navigators_db`.`navigators` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `navigators_db`.`trips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `navigators_db`.`trips` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `navigator_id` BIGINT UNSIGNED NOT NULL,
  `travel_type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trips_navigators_idx` (`navigator_id` ASC) VISIBLE,
  UNIQUE INDEX `travel_type_UNIQUE` (`travel_type` ASC) VISIBLE,
  CONSTRAINT `fk_trips_navigators`
    FOREIGN KEY (`navigator_id`)
    REFERENCES `navigators_db`.`navigators` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `navigators_db`.`points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `navigators_db`.`points` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(50) NOT NULL,
  `index` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `city_UNIQUE` (`city` ASC) VISIBLE,
  UNIQUE INDEX `index_UNIQUE` (`index` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `navigators_db`.`routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `navigators_db`.`routes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trip_id` BIGINT UNSIGNED NOT NULL,
  `distance` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_routes_trips1_idx` (`trip_id` ASC) VISIBLE,
  UNIQUE INDEX `distance_UNIQUE` (`distance` ASC) VISIBLE,
  CONSTRAINT `fk_routes_trips1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `navigators_db`.`trips` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `navigators_db`.`route_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `navigators_db`.`route_points` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `route_id` BIGINT UNSIGNED NOT NULL,
  `point_id` BIGINT UNSIGNED NOT NULL,
  INDEX `fk_routes_has_points_points1_idx` (`point_id` ASC) VISIBLE,
  INDEX `fk_routes_has_points_routes1_idx` (`route_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_routes_has_points_routes1`
    FOREIGN KEY (`route_id`)
    REFERENCES `navigators_db`.`routes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_routes_has_points_points1`
    FOREIGN KEY (`point_id`)
    REFERENCES `navigators_db`.`points` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
