insert into points(city, indx, value) values ('Slutsk', 223604, 0); 
insert into points(city, indx, value) values ('Semezhevo', 223932, 0);        
insert into points(city, indx, value) values ('Soligorsk', 223710, 0);      
insert into points(city, indx, value) values ('Lyuban', 223812, 0);        
insert into points(city, indx, value) values ('Kletsk', 222531, 0);        
insert into points(city, indx, value) values ('Nesvizh', 222603, 0);        
insert into points(city, indx, value) values ('Kopil', 223927, 0);          
insert into points(city, indx, value) values ('Old roads', 222932, 0);          
insert into points(city, indx, value) values ('Stolbtsi', 222666, 0);
insert into points(city, indx, value) values ('Uzda', 223411, 0);
insert into points(city, indx, value) values ('Hotlyany', 223414, 0);
insert into points(city, indx, value) values ('Seletsk', 222817, 0);
insert into points(city, indx, value) values ('Derzhinsk', 222712, 0);
insert into points(city, indx, value) values ('Lake', 223417, 0);
insert into points(city, indx, value) values ('Maryina Gorka', 222810, 0);
insert into points(city, indx, value) values ('Osipovichi', 213759, 0);
insert into points(city, indx, value) values ('Volozhin', 222357, 0);
insert into points(city, indx, value) values ('Zaslavl', 223034, 0);
insert into points(city, indx, value) values ('Minsk', 220005, 0);
insert into points(city, indx, value) values ('Cherven', 223232, 0);
insert into points(city, indx, value) values ('Berezino', 223311, 0);
insert into points(city, indx, value) values ('Rudnja', 247755, 0);
insert into points(city, indx, value) values ('Smolevichi', 222201, 0);
insert into points(city, indx, value) values ('Olekhovichi', 222323, 0);
insert into points(city, indx, value) values ('Molodechno', 222306, 0);
insert into points(city, indx, value) values ('Logoisk', 223141, 0);
insert into points(city, indx, value) values ('Zhodino', 222167, 0);
insert into points(city, indx, value) values ('Borisov', 222511, 0);
insert into points(city, indx, value) values ('Krupki', 222001, 0);
insert into points(city, indx, value) values ('Plestshinitsi', 223130, 0);
insert into points(city, indx, value) values ('Vileyka', 222412, 0);
insert into points(city, indx, value) values ('Myadel', 222397, 0);

insert into bus_routes(name) values ('Stolbtsi-Derzhinsk-Minsk-Smolevichi-Krupki');
insert into bus_routes(name) values ('Volozhin-Zaslavl-Minsk-Cherven-Berezino');
insert into bus_routes(name) values ('Molodechno-Olekhovichi-Minsk-Osipovichi');
insert into bus_routes(name) values ('Myadel-Logoisk-Minsk-Lake-Hotlyany-Slutsk');
insert into bus_routes(name) values ('Krupki-Borisov-Zhodino-Smolevichi-Minsk-Derzhinsk');
insert into bus_routes(name) values ('Zaslavl-Olekhovichi-Logoisk-Smolevichi-Cherven');

insert into bus_route_points(point_id, bus_route_id) values (9, 1);
insert into bus_route_points(point_id, bus_route_id) values (13, 1);
insert into bus_route_points(point_id, bus_route_id) values (19, 1);
insert into bus_route_points(point_id, bus_route_id) values (23, 1);
insert into bus_route_points(point_id, bus_route_id) values (29, 1);
insert into bus_route_points(point_id, bus_route_id) values (17, 2);
insert into bus_route_points(point_id, bus_route_id) values (18, 2);
insert into bus_route_points(point_id, bus_route_id) values (19, 2);
insert into bus_route_points(point_id, bus_route_id) values (20, 2);
insert into bus_route_points(point_id, bus_route_id) values (21, 2);
insert into bus_route_points(point_id, bus_route_id) values (25, 3);
insert into bus_route_points(point_id, bus_route_id) values (24, 3);
insert into bus_route_points(point_id, bus_route_id) values (19, 3);
insert into bus_route_points(point_id, bus_route_id) values (16, 3);
insert into bus_route_points(point_id, bus_route_id) values (32, 4);
insert into bus_route_points(point_id, bus_route_id) values (26, 4);
insert into bus_route_points(point_id, bus_route_id) values (19, 4);
insert into bus_route_points(point_id, bus_route_id) values (14, 4);
insert into bus_route_points(point_id, bus_route_id) values (11, 4);
insert into bus_route_points(point_id, bus_route_id) values (1, 4);
insert into bus_route_points(point_id, bus_route_id) values (29, 5);
insert into bus_route_points(point_id, bus_route_id) values (28, 5);
insert into bus_route_points(point_id, bus_route_id) values (27, 5);
insert into bus_route_points(point_id, bus_route_id) values (23, 5);
insert into bus_route_points(point_id, bus_route_id) values (19, 5);
insert into bus_route_points(point_id, bus_route_id) values (13, 5);
insert into bus_route_points(point_id, bus_route_id) values (18, 6);
insert into bus_route_points(point_id, bus_route_id) values (24, 6);
insert into bus_route_points(point_id, bus_route_id) values (26, 6);
insert into bus_route_points(point_id, bus_route_id) values (23, 6);
insert into bus_route_points(point_id, bus_route_id) values (20, 6);